function stim = LoadMovie(filename, varargin)
% This function loads a movie from a file.  The movie can be static
% and described in a .mat file, or dynamically generated by a .m file.
% However, the movie must be described by the following structure:
%
% m.x_res - the number of x pixels (scalar)
% m.y_res - the number of y pixels (scalar)
% m.colmap - the color mappings for each value in the stimulus 
%            (Nx3 array, N == max(max(m.stimulus)))
% m.stimulus - the movie, which should be an x_res by y_res by n_frames array of doubles
%
% Usage: stim = LoadMovie(filename, [args])
%        filename - the .mat or .m file to load the stimulus from
%        args - additional arguments which will be supplied if filename points to an mfile
%
% $Id$
% load the stimulus
[pn func ext] = fileparts(filename);
switch lower(ext)
case '.m'
    if exist(func, 'file') > 0
        if nargin == 1
            stim = feval(func);
        else
            stim = feval(func,varargin{:});
        end
    else
        error('Invalid .m file!');
    end
case '.mat'
    if exist(filename, 'file') > 0
        stim = load(filename);
    else
        error('Invalid .mat file!');        
    end
otherwise
    error('Invalid stimulus file.');
end

% check structure of stimulus
fields = {'x_res','y_res','stimulus'};
for i = 1:length(fields)
    j = isfield(stim,fields{i});
    if ~j
        error([fields{i} ' is a required field.']);
    end
end
if isfield(stim,'colmap')
    colmap = getfield(stim,'colmap');
    N = max(max(max(stim.stimulus)));
    S = size(colmap);
    if ~all(S == [N 3])
        error('Wrong dimensions for colormap');
    end
else
    error('colmap is a required field.');
end