function stim = LoadMovie(filename, varargin)
% This function loads a movie from a file.  The movie can be static
% and described in a .mat file, or dynamically generated by a .m file.
%
%
%
% Usage: stim = LoadMovie(filename, [args])
%        filename - the .mat or .m file to load the stimulus from
%        args - additional arguments which will be supplied if filename points to an mfile
%
% See Also:
%        headers/stim_struct.m - The stimulus structure
%
% $Id$
% load the stimulus
[pn func ext] = fileparts(filename);
switch lower(ext)
case '.m'
    if exist(func, 'file') > 0
        if nargin == 1
            stim = feval(func);
        else
            stim = feval(func,varargin{:});
        end
    else
        error('Invalid .m file!');
    end
case {'.mat', '.s0', '.s1'}
    if exist(filename, 'file') > 0
        stim = LoadStimulusFile(filename);
    else
        error('Invalid .mat file!');
    end
otherwise
    error('Invalid stimulus file.');
end

% check structure of stimulus
fields = {'x_res','y_res','colmap'};
for i = 1:length(fields)
    j = isfield(stim,fields{i});
    if ~j
        error([fields{i} ' is a required field.']);
    end
end
if ~isfield(stim,'stimulus') & ~isfield(stim,'param')
    error('A .stimulus or .param field is required');
end
if isfield(stim,'stimulus')
    colmap = getfield(stim,'colmap');
    N = max(max(max(stim.stimulus)));
    S = size(colmap);
    if ~all(S == [N 3])
        error('Wrong dimensions for colormap');
    end
end